
name: Optimize Content on Publish

on:
  push:
    branches: [ main ]
    paths: 
      - 'posts/**'
      - 'public/images/**'
  workflow_dispatch:

jobs:
  optimize:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install sharp for image optimization
      run: npm install sharp
    
    - name: Run content optimization
      run: node scripts/auto-optimize-content.js
    
    - name: Optimize existing images
      run: node scripts/optimize-images.js
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit optimized content
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "🖼️ Auto-optimize images and content [skip ci]"
        git push
